version: "2"
services:
  nate-api:
    build:
      dockerfile: api-src/Dockerfile
      context: .
      args:
        SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
    volumes:
      - ./api-src:/usr/src/service
    working_dir: /usr/src/service
    command: bash -c "npm install"

  nate-webclient:
    build:
      dockerfile: web-src/Dockerfile
      context: .
      args:
        SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
    volumes:
      - ./web-src:/usr/src/service
    working_dir: /usr/src/service
    command: bash -c "npm install"
