version: "3"
services:
  nate-challenge:
    container_name: nate-challenge
    restart: unless-stopped
    build:
      dockerfile: api-src/Dockerfile
      context: ./
      args:
        SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
    volumes:
      - ./api-src:/usr/src/service
    working_dir: /usr/src/service
    ports:
      - "3000:3000"
    command: >
      sh -c "npm start"

  nate-webclient:
    container_name: nate-webclient
    restart: unless-stopped
    build:
      dockerfile: web-src/Dockerfile
      context: ./
      args:
        SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
    volumes:
      - ./web-src:/usr/src/service
    working_dir: /usr/src/service
    ports:
      - "80:3000"
    command: >
      sh -c "npm start"
